# Generated by Django 5.0.6 on 2024-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mainmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='video',
            field=models.FileField(upload_to='media/videos'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='voice',
            field=models.FileField(upload_to='media/audios'),
        ),
    ]
